### ISSUE TITLE
Store Recovery Version Number

### ISSUE THREAD

**Issue by ameer1234567890** [PhilZ-cwm6/philz_touch_cwm6#1]
The recovery should store its version number in a text file like `/sdcard/clockworkmod/.recovery_version` or something similar. This practice is being followed by CWM as well as TWRP. See this: https://github.com/CyanogenMod/android_bootable_recovery/commit/edc87090bab7709a1a1ccd19c46ea68a55fcde9a

**Comment by PhilZ-cwm6** [comment]
done
