### ISSUE TITLE
Recovery crashes with f2fs, nandroid restore.

### ISSUE THREAD

**Issue by arter97** [PhilZ-cwm6/philz_touch_cwm6#34]
Backing up f2fs partitions are working fine, but the recovery(latest git revision) crashes when recovering f2fs partitions.

After calling mkfs.f2fs, the recovery crashes and reloads.

So, /data restore is working fine(since it's just a 'delete recursive' method), but /system and /cache restore is not working.

Here's a brief log ;

> > Restoring /cache...
> > couldn't find old .img format
> > Found new backup image: /sdcard/clockworkmod/backup/2014-03-11.20.57.55_11-20140424-NIGHTLY-ks01lte/cache.f2fs.tar
> > I:setting up /data/media(/0) for /sdcard/clockworkmod/.hidenandroidprogress.
> > I:using /data/media/0 for /sdcard
> > Restoring cache...

```
F2FS-tools: mkfs.f2fs Ver: 1.3.0 (2014-02-06)
```

Starting recovery on (UTC) Tue Mar 11 20:58:13 2014

**Comment by arter97** [comment]
PS. Wiping f2fs partitions on Mount & Storage are working fine.

**Comment by PhilZ-cwm6** [comment]
ask dev who released your device version

**Comment by arter97** [comment]
Hmm.. I've compiled it myself.

I haven't done any source-code editing, just modified BoardConfig.mk to define TARGET_USERIMAGES_USE_F2FS.

**Comment by arter97** [comment]
ps. ks01lte is the same as hlte. The recovery is compatible.

**Comment by PhilZ-cwm6** [comment]
currently, I do not directly support f2fs. There are devs that added it without issues to recovery. Look at their git

Also, check gerrit: there are ongoing functional patches to merge it into vold
